// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzkxiiZJPB8V01u4-_PKoPckoLkb6lPsg',
    appId: '1:864314561640:web:4ad8c9574724eb0935d7dd',
    messagingSenderId: '864314561640',
    projectId: 'wisyapp',
    authDomain: 'wisyapp.firebaseapp.com',
    storageBucket: 'wisyapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAry-bpkM6yUtuJAt5Vn2ARv1i0bZEQ3Qk',
    appId: '1:864314561640:android:d57c51a588d82be535d7dd',
    messagingSenderId: '864314561640',
    projectId: 'wisyapp',
    storageBucket: 'wisyapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy1scE4JuAiMuO3PT3cRLaVPPBbMgd-MM',
    appId: '1:864314561640:ios:00a39792677c07bd35d7dd',
    messagingSenderId: '864314561640',
    projectId: 'wisyapp',
    storageBucket: 'wisyapp.appspot.com',
    iosBundleId: 'com.example.wisyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy1scE4JuAiMuO3PT3cRLaVPPBbMgd-MM',
    appId: '1:864314561640:ios:7cb7463da3ac5ea435d7dd',
    messagingSenderId: '864314561640',
    projectId: 'wisyapp',
    storageBucket: 'wisyapp.appspot.com',
    iosBundleId: 'com.example.wisyApp.RunnerTests',
  );
}
